kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: move-webapp-vmware-vm-26001-l2rxq
  namespace: openshift-gitops
  ownerReferences:
    - apiVersion: kubevirt.io/v1
      kind: VirtualMachine
      name: database-user1
      uid: dca554d8-2439-482d-a7f4-bc1bb4596935
      controller: false
      blockOwnerDeletion: true
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.18.8
    migration: 461e4278-93bf-4e10-8785-343a591af48d
    plan: 70a24f37-288b-4816-bc79-bdcc6e731424
    vmID: vm-26001
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '4831838208'
  volumeName: pvc-6fe6569e-2ea8-4706-8bc6-61c245cda5a7
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Block
  dataSource:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: volume-import-source-1df7d599-c238-4485-ae04-620fb30f3c2f
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: volume-import-source-1df7d599-c238-4485-ae04-620fb30f3c2f
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: move-webapp-vmware-vm-26001-xv22l
  namespace: openshift-gitops
  ownerReferences:
    - apiVersion: kubevirt.io/v1
      kind: VirtualMachine
      name: database-user1
      uid: dca554d8-2439-482d-a7f4-bc1bb4596935
      controller: false
      blockOwnerDeletion: true
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.18.8
    migration: 461e4278-93bf-4e10-8785-343a591af48d
    plan: 70a24f37-288b-4816-bc79-bdcc6e731424
    vmID: vm-26001
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '1073741824'
  volumeName: pvc-4a75edf2-580e-4aaa-ab66-0df0ca9db662
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Block
  dataSource:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: volume-import-source-05a26f14-8e9c-4aad-ae96-9f87981095d3
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: volume-import-source-05a26f14-8e9c-4aad-ae96-9f87981095d3
